name = "Rosmontic"
babel = ["zh", "en"]

[contact]
email = "Rosmontis233@hotmail.com"
telegram = "Rosmontis233"
twitter = "Rosmontis233"
github = "Rosmontis2333"

[persona]
pgp = "3CFE FAB3 CAC1 CC73 5D67 DF41 BFFB 7708 8E66 43DC"
