[NeoPDP-11]
asn = 4201270000
cidr = ["10.127.1.1/24", "10.127.254.1/24", "10.127.255.1/32"]

[NeoSystem]
asn = 4201270000
cidr = ["10.127.1.80/24", "10.127.2.1/24", "10.127.255.80/32"]

[pan]
asn = 4201270000
cidr = ["10.127.3.1/24"]

[ucbvax]
asn = 4201270000

[NeoVAX]
asn = 4201270000
cidr = ["10.127.2.22/30"]
