["10.127.30.0/24"]
type = "subnet"
name = "HWARP-NEO-IP4-NETWORK"
description = "Hwarp NeoNetwork - IPv4"

["fd10:127:30::/48"]
type = "subnet"
name = "HWARP-NEO-IP6-NETWORK"
description = "Hwarp NeoNetwork - IPv6"

