["10.127.8.192/26"]
type = "subnet"
name = "JerryXiao-Infrastructure"
description = "For cloud instances"

["10.127.9.0/24"]
type = "subnet"
name = "JerryXiao-Home"
description = "For home"

["10.127.8.64/26"]
type = "subnet"
name = "JerryXiao-School"
description = "For school"

["10.127.255.53/32"]
type = "loopback"
name = "JerryXiao-Anycast"
description = "Anycast Recursive DNS"

["10.127.255.2/32"]
type = "loopback"
name = "JerryXiao-Anycast"
description = "Anycast Recursive DNS"

["fd10:127:53::/48"]
type = "subnet"
name = "JerryXiao6"
description = "JerryNet6"
