["10.127.0.0/24"]
type = "subnet"
name = "RESERVED"
description = "Reserved"

["10.127.1.0/24"]
type = "subnet"
name = "MAIN"
description = "LAN 1"

["10.127.2.0/24"]
type = "subnet"
name = "Messed-up Network"

["10.127.16.0/24"]
type = "subnet"
name = "Neo_Chen ZeroTier-One Hub"
description = ""

["10.127.110.0/24"]
type = "subnet"
name = "BS-Net"
description = "BS satellite TV streaming network"

["10.127.255.4/32"]
type = "loopback"
name = "fsnvax"
description = "Debian/frr"

["fd10:127:5f37:59df::/64"]
type = "subnet"
name = "NeoNetwork Origin"
description = "Neo_Chens Network"
