["10.127.237.0/24"]
type = "subnet"
name = "MagicNeko IX (Will not broadcast)"
description = "For Magicneko Explosion Network Interworking address, No SLA"

["10.127.255.117/32"]
type = "loopback"
name = "magicneko-tw"
description = "magicneko-tw/frr"

["fd10:127:0233::/48"]
type = "subnet"
name = "icecat"
description = "Magicneko ipv6 reserved segment"

["10.127.255.54/32"]
type = "loopback"
name = "anycast-recur-4"
description = "Anycast recursive DNS"

["fd10:127:53:53::/64"]
type = "loopback"
name = "anycast-recur-6"
description = "Anycast recursive DNS"
supernet = "fd10:127:53::/48"

["10.127.255.18/32"]
type = "loopback"
name = "Video encoding node(Anycast)"
description = "Video encoding node, used to monitor (Cyan) online live broadcast in the live room and record encoding"
