["10.127.0.0/24"]
type = "subnet"
name = "RESERVED"
description = "Reserved"

["10.127.1.0/24"]
type = "subnet"
name = "CROOM"
description = "LAN at school"

["10.127.2.0/24"]
type = "subnet"
name = "NeoSystem"

["10.127.3.0/24"]
type = "subnet"
name = "pan hub"
description = "For non-multihome connection in Taiwan"

["10.127.16.0/24"]
type = "subnet"
name = "Neo_Chen ZeroTier-One Hub"
description = ""

["10.127.255.1/32"]
type = "loopback"
name = "NeoPDP-11"
description = "FreeBSD/frr"

["10.127.255.2/32"]
type = "loopback"
name = "ucbvax"
description = "Arch Linux/frr"

["10.127.255.4/32"]
type = "loopback"
name = "pan"
description = "Arch Linux/frr"

["10.127.255.80/32"]
type = "loopback"
name = "NeoSystem"
description = "Arch Linux/frr"

["fd10:127:5f37:59df::/64"]
type = "subnet"
name = "NeoNetwork Origin"
description = "Neo_Chens Network"

["fd10:127::/64"]
type = "subnet"
name = "Neo_Chen ZeroTier-One IPv6 Hub"
description = ""
