["10.127.21.0/24"]
type = "subnet"
name = "IEDON-NET"
description = "iEdon Networks - Backbone and branches"

["10.127.89.0/24"]
type = "subnet"
name = "IEDON-NET"
description = "iEdon Networks - Backbone and branches"
